name: aod3
description: Aragon Open Data 3.0 basado en AngularDart2
version: 0.0.1
environment:
  sdk: '>=1.8.0 <=2.3.0'
dependencies:
  angular2: 3.0.0-alpha
  dart_sass_transformer: any
  angular2_components: 0.3.1-alpha
  fluri: any
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions:
          - --show-package-warnings
          - --dump-info
          - --trust-primitives
          - --trust-type-annotations
          - --enable-diagnostic-colors
          - --minify
          - --terse
          - --checked
          - --enable-checked-mode
- dart_to_js_script_rewriter
- dart_sass_transformer:
   executable: /home/eder/BourbonSassTest/sassc/bin/sassc      # Sass executable to use
   line-numbers: false            # Include line numbers in output
   style: compressed                # Style of generated CSS
   copy-sources: false            # Copy original .scss/.sass files to out
